// lib/utils/country_data.dart

class CountryData {
  final String name;
  final String flagCode;

  const CountryData({required this.name, required this.flagCode});
}

class CountryHelper {
  // Comprehensive list of countries with their flag codes
  // These codes match your server's available flags
  static const List<CountryData> countries = [
    // Major countries (matching your server's AVAILABLE_FLAGS)
    CountryData(name: 'International', flagCode: 'international'),
    CountryData(name: 'United States', flagCode: 'us'),
    CountryData(name: 'United Kingdom', flagCode: 'uk'),
    CountryData(name: 'Canada', flagCode: 'ca'),
    CountryData(name: 'Australia', flagCode: 'au'),
    CountryData(name: 'Germany', flagCode: 'de'),
    CountryData(name: 'France', flagCode: 'fr'),
    CountryData(name: 'Italy', flagCode: 'it'),
    CountryData(name: 'Spain', flagCode: 'es'),
    CountryData(name: 'Japan', flagCode: 'jp'),
    CountryData(name: 'South Korea', flagCode: 'kr'),
    CountryData(name: 'China', flagCode: 'cn'),
    CountryData(name: 'India', flagCode: 'in'),
    CountryData(name: 'Brazil', flagCode: 'br'),
    CountryData(name: 'Mexico', flagCode: 'mx'),
    CountryData(name: 'Russia', flagCode: 'ru'),
    CountryData(name: 'South Africa', flagCode: 'za'),
    CountryData(name: 'Egypt', flagCode: 'eg'),
    CountryData(name: 'Nigeria', flagCode: 'ng'),
    CountryData(name: 'Argentina', flagCode: 'ar'),
    CountryData(name: 'Chile', flagCode: 'cl'),
    CountryData(name: 'Peru', flagCode: 'pe'),
    CountryData(name: 'Sweden', flagCode: 'se'),
    CountryData(name: 'Norway', flagCode: 'no'),
    CountryData(name: 'Denmark', flagCode: 'dk'),
    CountryData(name: 'Finland', flagCode: 'fi'),
    CountryData(name: 'Netherlands', flagCode: 'nl'),
    CountryData(name: 'Belgium', flagCode: 'be'),
    CountryData(name: 'Switzerland', flagCode: 'ch'),
    CountryData(name: 'Austria', flagCode: 'at'),
    CountryData(name: 'Portugal', flagCode: 'pt'),
    CountryData(name: 'Ireland', flagCode: 'ie'),
    CountryData(name: 'Poland', flagCode: 'pl'),
    CountryData(name: 'Czech Republic', flagCode: 'cz'),
    CountryData(name: 'Hungary', flagCode: 'hu'),
    CountryData(name: 'Greece', flagCode: 'gr'),
    CountryData(name: 'Turkey', flagCode: 'tr'),
    CountryData(name: 'Israel', flagCode: 'il'),
    CountryData(name: 'United Arab Emirates', flagCode: 'ae'),
    CountryData(name: 'Saudi Arabia', flagCode: 'sa'),
    CountryData(name: 'Thailand', flagCode: 'th'),
    CountryData(name: 'Vietnam', flagCode: 'vn'),
    CountryData(name: 'Indonesia', flagCode: 'id'),
    CountryData(name: 'Malaysia', flagCode: 'my'),
    CountryData(name: 'Singapore', flagCode: 'sg'),
    CountryData(name: 'Philippines', flagCode: 'ph'),

    // Additional countries for comprehensive coverage (using generic 'international' flag)
    // These will use the international flag but still allow country selection
    CountryData(name: 'Afghanistan', flagCode: 'international'),
    CountryData(name: 'Albania', flagCode: 'international'),
    CountryData(name: 'Algeria', flagCode: 'international'),
    CountryData(name: 'Andorra', flagCode: 'international'),
    CountryData(name: 'Angola', flagCode: 'international'),
    CountryData(name: 'Antigua and Barbuda', flagCode: 'international'),
    CountryData(name: 'Armenia', flagCode: 'international'),
    CountryData(name: 'Azerbaijan', flagCode: 'international'),
    CountryData(name: 'Bahamas', flagCode: 'international'),
    CountryData(name: 'Bahrain', flagCode: 'international'),
    CountryData(name: 'Bangladesh', flagCode: 'international'),
    CountryData(name: 'Barbados', flagCode: 'international'),
    CountryData(name: 'Belarus', flagCode: 'international'),
    CountryData(name: 'Belize', flagCode: 'international'),
    CountryData(name: 'Benin', flagCode: 'international'),
    CountryData(name: 'Bhutan', flagCode: 'international'),
    CountryData(name: 'Bolivia', flagCode: 'international'),
    CountryData(name: 'Bosnia and Herzegovina', flagCode: 'international'),
    CountryData(name: 'Botswana', flagCode: 'international'),
    CountryData(name: 'Brunei', flagCode: 'international'),
    CountryData(name: 'Bulgaria', flagCode: 'international'),
    CountryData(name: 'Burkina Faso', flagCode: 'international'),
    CountryData(name: 'Burundi', flagCode: 'international'),
    CountryData(name: 'Cambodia', flagCode: 'international'),
    CountryData(name: 'Cameroon', flagCode: 'international'),
    CountryData(name: 'Cape Verde', flagCode: 'international'),
    CountryData(name: 'Central African Republic', flagCode: 'international'),
    CountryData(name: 'Chad', flagCode: 'international'),
    CountryData(name: 'Colombia', flagCode: 'international'),
    CountryData(name: 'Comoros', flagCode: 'international'),
    CountryData(name: 'Congo', flagCode: 'international'),
    CountryData(name: 'Costa Rica', flagCode: 'international'),
    CountryData(name: 'Croatia', flagCode: 'international'),
    CountryData(name: 'Cuba', flagCode: 'international'),
    CountryData(name: 'Cyprus', flagCode: 'international'),
    CountryData(name: 'Djibouti', flagCode: 'international'),
    CountryData(name: 'Dominica', flagCode: 'international'),
    CountryData(name: 'Dominican Republic', flagCode: 'international'),
    CountryData(name: 'East Timor', flagCode: 'international'),
    CountryData(name: 'Ecuador', flagCode: 'international'),
    CountryData(name: 'El Salvador', flagCode: 'international'),
    CountryData(name: 'Equatorial Guinea', flagCode: 'international'),
    CountryData(name: 'Eritrea', flagCode: 'international'),
    CountryData(name: 'Estonia', flagCode: 'international'),
    CountryData(name: 'Eswatini', flagCode: 'international'),
    CountryData(name: 'Ethiopia', flagCode: 'international'),
    CountryData(name: 'Fiji', flagCode: 'international'),
    CountryData(name: 'Gabon', flagCode: 'international'),
    CountryData(name: 'Gambia', flagCode: 'international'),
    CountryData(name: 'Georgia', flagCode: 'international'),
    CountryData(name: 'Ghana', flagCode: 'international'),
    CountryData(name: 'Grenada', flagCode: 'international'),
    CountryData(name: 'Guatemala', flagCode: 'international'),
    CountryData(name: 'Guinea', flagCode: 'international'),
    CountryData(name: 'Guinea-Bissau', flagCode: 'international'),
    CountryData(name: 'Guyana', flagCode: 'international'),
    CountryData(name: 'Haiti', flagCode: 'international'),
    CountryData(name: 'Honduras', flagCode: 'international'),
    CountryData(name: 'Iceland', flagCode: 'international'),
    CountryData(name: 'Iran', flagCode: 'international'),
    CountryData(name: 'Iraq', flagCode: 'international'),
    CountryData(name: 'Ivory Coast', flagCode: 'international'),
    CountryData(name: 'Jamaica', flagCode: 'international'),
    CountryData(name: 'Jordan', flagCode: 'international'),
    CountryData(name: 'Kazakhstan', flagCode: 'international'),
    CountryData(name: 'Kenya', flagCode: 'international'),
    CountryData(name: 'Kiribati', flagCode: 'international'),
    CountryData(name: 'Kuwait', flagCode: 'international'),
    CountryData(name: 'Kyrgyzstan', flagCode: 'international'),
    CountryData(name: 'Laos', flagCode: 'international'),
    CountryData(name: 'Latvia', flagCode: 'international'),
    CountryData(name: 'Lebanon', flagCode: 'international'),
    CountryData(name: 'Lesotho', flagCode: 'international'),
    CountryData(name: 'Liberia', flagCode: 'international'),
    CountryData(name: 'Libya', flagCode: 'international'),
    CountryData(name: 'Liechtenstein', flagCode: 'international'),
    CountryData(name: 'Lithuania', flagCode: 'international'),
    CountryData(name: 'Luxembourg', flagCode: 'international'),
    CountryData(name: 'Madagascar', flagCode: 'international'),
    CountryData(name: 'Malawi', flagCode: 'international'),
    CountryData(name: 'Maldives', flagCode: 'international'),
    CountryData(name: 'Mali', flagCode: 'international'),
    CountryData(name: 'Malta', flagCode: 'international'),
    CountryData(name: 'Marshall Islands', flagCode: 'international'),
    CountryData(name: 'Mauritania', flagCode: 'international'),
    CountryData(name: 'Mauritius', flagCode: 'international'),
    CountryData(name: 'Micronesia', flagCode: 'international'),
    CountryData(name: 'Moldova', flagCode: 'international'),
    CountryData(name: 'Monaco', flagCode: 'international'),
    CountryData(name: 'Mongolia', flagCode: 'international'),
    CountryData(name: 'Montenegro', flagCode: 'international'),
    CountryData(name: 'Morocco', flagCode: 'international'),
    CountryData(name: 'Mozambique', flagCode: 'international'),
    CountryData(name: 'Myanmar', flagCode: 'international'),
    CountryData(name: 'Namibia', flagCode: 'international'),
    CountryData(name: 'Nauru', flagCode: 'international'),
    CountryData(name: 'Nepal', flagCode: 'international'),
    CountryData(name: 'New Zealand', flagCode: 'international'),
    CountryData(name: 'Nicaragua', flagCode: 'international'),
    CountryData(name: 'Niger', flagCode: 'international'),
    CountryData(name: 'North Korea', flagCode: 'international'),
    CountryData(name: 'North Macedonia', flagCode: 'international'),
    CountryData(name: 'Oman', flagCode: 'international'),
    CountryData(name: 'Pakistan', flagCode: 'international'),
    CountryData(name: 'Palau', flagCode: 'international'),
    CountryData(name: 'Palestine', flagCode: 'international'),
    CountryData(name: 'Panama', flagCode: 'international'),
    CountryData(name: 'Papua New Guinea', flagCode: 'international'),
    CountryData(name: 'Paraguay', flagCode: 'international'),
    CountryData(name: 'Qatar', flagCode: 'international'),
    CountryData(name: 'Romania', flagCode: 'international'),
    CountryData(name: 'Rwanda', flagCode: 'international'),
    CountryData(name: 'Saint Kitts and Nevis', flagCode: 'international'),
    CountryData(name: 'Saint Lucia', flagCode: 'international'),
    CountryData(
      name: 'Saint Vincent and the Grenadines',
      flagCode: 'international',
    ),
    CountryData(name: 'Samoa', flagCode: 'international'),
    CountryData(name: 'San Marino', flagCode: 'international'),
    CountryData(name: 'Sao Tome and Principe', flagCode: 'international'),
    CountryData(name: 'Senegal', flagCode: 'international'),
    CountryData(name: 'Serbia', flagCode: 'international'),
    CountryData(name: 'Seychelles', flagCode: 'international'),
    CountryData(name: 'Sierra Leone', flagCode: 'international'),
    CountryData(name: 'Slovakia', flagCode: 'international'),
    CountryData(name: 'Slovenia', flagCode: 'international'),
    CountryData(name: 'Solomon Islands', flagCode: 'international'),
    CountryData(name: 'Somalia', flagCode: 'international'),
    CountryData(name: 'Sri Lanka', flagCode: 'international'),
    CountryData(name: 'Sudan', flagCode: 'international'),
    CountryData(name: 'Suriname', flagCode: 'international'),
    CountryData(name: 'Syria', flagCode: 'international'),
    CountryData(name: 'Taiwan', flagCode: 'international'),
    CountryData(name: 'Tajikistan', flagCode: 'international'),
    CountryData(name: 'Tanzania', flagCode: 'international'),
    CountryData(name: 'Togo', flagCode: 'international'),
    CountryData(name: 'Tonga', flagCode: 'international'),
    CountryData(name: 'Trinidad and Tobago', flagCode: 'international'),
    CountryData(name: 'Tunisia', flagCode: 'international'),
    CountryData(name: 'Turkmenistan', flagCode: 'international'),
    CountryData(name: 'Tuvalu', flagCode: 'international'),
    CountryData(name: 'Uganda', flagCode: 'international'),
    CountryData(name: 'Ukraine', flagCode: 'international'),
    CountryData(name: 'Uruguay', flagCode: 'international'),
    CountryData(name: 'Uzbekistan', flagCode: 'international'),
    CountryData(name: 'Vanuatu', flagCode: 'international'),
    CountryData(name: 'Vatican City', flagCode: 'international'),
    CountryData(name: 'Venezuela', flagCode: 'international'),
    CountryData(name: 'Yemen', flagCode: 'international'),
    CountryData(name: 'Zambia', flagCode: 'international'),
    CountryData(name: 'Zimbabwe', flagCode: 'international'),
  ];

  // Map of country codes to flag emojis for display purposes
  static const Map<String, String> flagEmojis = {
    'international': '🌍',
    'us': '🇺🇸',
    'uk': '🇬🇧',
    'ca': '🇨🇦',
    'au': '🇦🇺',
    'de': '🇩🇪',
    'fr': '🇫🇷',
    'it': '🇮🇹',
    'es': '🇪🇸',
    'jp': '🇯🇵',
    'kr': '🇰🇷',
    'cn': '🇨🇳',
    'in': '🇮🇳',
    'br': '🇧🇷',
    'mx': '🇲🇽',
    'ru': '🇷🇺',
    'za': '🇿🇦',
    'eg': '🇪🇬',
    'ng': '🇳🇬',
    'ar': '🇦🇷',
    'cl': '🇨🇱',
    'pe': '🇵🇪',
    'se': '🇸🇪',
    'no': '🇳🇴',
    'dk': '🇩🇰',
    'fi': '🇫🇮',
    'nl': '🇳🇱',
    'be': '🇧🇪',
    'ch': '🇨🇭',
    'at': '🇦🇹',
    'pt': '🇵🇹',
    'ie': '🇮🇪',
    'pl': '🇵🇱',
    'cz': '🇨🇿',
    'hu': '🇭🇺',
    'gr': '🇬🇷',
    'tr': '🇹🇷',
    'il': '🇮🇱',
    'ae': '🇦🇪',
    'sa': '🇸🇦',
    'th': '🇹🇭',
    'vn': '🇻🇳',
    'id': '🇮🇩',
    'my': '🇲🇾',
    'sg': '🇸🇬',
    'ph': '🇵🇭',
  };

  // Helper method to get flag emoji
  static String getFlagEmoji(String flagCode) {
    return flagEmojis[flagCode] ?? '🌍';
  }

  // Helper method to get country by flag code
  static CountryData? getCountryByFlagCode(String flagCode) {
    try {
      return countries.firstWhere((country) => country.flagCode == flagCode);
    } catch (e) {
      return null;
    }
  }

  // Helper method to get all countries with specific flags (not international)
  static List<CountryData> getCountriesWithSpecificFlags() {
    return countries
        .where((country) => country.flagCode != 'international')
        .toList();
  }
}
