# Snapfile — device list for Fastlane snapshot
# (Only used if you switch to the native `snapshot` action)

devices([
  "iPhone 16 Pro Max",
  "iPhone 11 Pro Max",
])

languages([
  "en-US",
])

output_directory("./screenshots")
clear_previous_screenshots(true)
